[project]
name = "ai-crm-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.76.0",
    "streamlit>=1.45.0",
]
